# Generated by Django 5.2.3 on 2025-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='faculty_resource_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
