# Generated by Django 5.2.3 on 2025-07-16 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_doubt_faculty_resource_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('WEB', 'Web Development'), ('ML', 'Machine Learning'), ('PY', 'Python'), ('JAVA', 'Java'), ('OTH', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='resource_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
