# Generated by Django 5.2.3 on 2025-07-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_doubt_is_public_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='faculty_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
