# Generated by Django 5.2.3 on 2025-07-14 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_doubt_faculty_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doubts', to=settings.AUTH_USER_MODEL),
        ),
    ]
