# Generated by Django 5.2.3 on 2025-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
